version: 2
jobs:
  build:
    working_directory: ~/learning
    docker:
      - image: cimg/ruby:3.0.0
      - environment:
          RAILS_ENV: test
    steps:
      - checkout
      - restore_cache:
          key: bundler-{{ checksum "Gemfile.lock" }}
      - run: gem install bundler
      - run: bundle install
      - run:
          name: Install dependencies
          command: |
            bundle install
      - save_cache:
          key: bundler-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.bundle